pregrasp_offset: 0.15
ee_offset: 0.15
orientation: [-90, 45, -90]
# init_pose: [75.048096, 432.961609, 396.784912, -90, 45, -90] # pose used during testing basket drop
# init_pose: [-79.132172, 421.766205, 506.757019, -90, 45, -90] # pose used during rosbag recording
# init_pose: [-79.132172, 421.766205, 356.757019, -90, 45, -90] # higher pose with mf now
init_pose: [-77, 425, 615, -90, 45, -90] # low init for seeing qr codes
to_basket_points: [[260, -40, 387, -90, 45, -90],
        [208, -125, 387, -90, 45, -108],
        [156, -210, 387, -90, 45, -126],
        [104, -295, 387, -90, 45, -144],
        [52, -380, 387, -90, 45, -162],
        [0, -465, 387, -90, 45, -180]]
from_basket_points: [[0, -465, 387, -90, 45, -180],
        [52, -380, 387, -90, 45, -162],
        [104, -295, 387, -90, 45, -144],
        [156, -210, 387, -90, 45, -126],
        [208, -125, 387, -90, 45, -108],
        [260, -40, 387, -90, 45, -90],
        [192, 53, 432, -90, 45, -90],
        [124, 146, 477, -90, 45, -90],
        [56, 239, 522, -90, 45, -90],
        [-12, 332, 567, -90, 45, -90],
        [-77, 425, 615, -90, 45, -90]]

# pre_basket: [259.871063, -41.030567, 387.286804, -83.478346, 44.873195, -72.777901]
# at_basket: [1.928574, -466.084991, 387.286835, -83.478346, 44.873195, -156.976685]